logging.level.org.springframework: DEBUG

spring:
  devtools:
    restart:
      additional-paths: /src
  config:
    import: optional:file:env.properties

server:
  port: 3000

app:
  db-pg:
    jdbc-url: jdbc:postgresql://${DB_PG_HOST}:${DB_PG_PORT}/${DB_PG_DATABASE}
    username: ${DB_PG_USER}
    password: ${DB_PG_PASSWORD}
    pool-size: 30

springdoc:
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha
    path: /api/swagger
  api-docs:
    path: /api/docs